### ISSUE TITLE
Problem with self-signed SSL certificate

### ISSUE THREAD

**Issue by pawelotto** [alallier/reload#147] opened 2018-01-04 09:31 UTC
I was unable to run this addon on a self-signed https://localhost
Some debugging here: 
```
WebSocket connection to 'wss://localhost:9856/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
(anonymous) @ reload.js:94
``` 
Any ideas how to fix this?

**Comment by alallier** [comment] 2018-01-04 13:12
This is a duplicate of #143, going to close. Head over to #143 to track progress leave comments as necessary. Short answer is it hasn't been solved yet

**Closed by alallier** 2018-01-04 13:12 UTC
Labels: bug, express application
