### ISSUE TITLE
Problems with set Hebrew char 

### ISSUE THREAD

**Issue by matanyacohen** [alallier/reload#200] opened 2019-07-05 04:33 UTC
I try with HTML have only:
the dady <bdi>מולו</bdi> went

I got on the browser:
the dady ×ž×•×œ×• went

I used with command line option:

>reload -v -b -d "H:\a-n-code-example\n\dist\public" -p 3000 -s "cc.html"

when I do:
>H:\a-n-code-example\n>node dist/server.js
every things show well.

**Comment by alallier** [comment] 2019-10-06 19:01
@matanyacohen can you provide a sample application or more information. I was not able to reproduce

**Comment by alallier** [comment] 2019-11-08 15:09
Closing for now due to lack of followup information. I'm happy to continue discussion here or re-open with more information!

**Closed by alallier** 2019-11-08 15:09 UTC
Labels: awaiting feedback
