### ISSUE TITLE
watch multiple directories?

### ISSUE THREAD

**Issue by andykais** [alallier/reload#261] opened 2020-08-03 16:16 UTC
Hi, is it possible to watch multiple directories? I have a project structure like so:

```
sample/
  index.html
build/
  index.js
src/
  index.ts
node_modules/
package.json
```
My development setup looks like this: `reload --browser --start-page 'sample/index.html' & tsc --watch`. I want to reload the browser whenever a file in the `sample` repo changes or a file in the `build` folder changes. Currently the best I can do is `reload --browser --start-page 'sample/index.html' --ext js,html & tsc --watch` but that is still needlessly watching the `node_modules` & `src` directories.

**Comment by alallier** [comment] 2020-08-04 12:44
Agreed it is a useful feature. Duplicate of #25 though so closing in favor of that. Feel free to add discussion there if you think it needs more information, pull requests welcome 😁

**Closed by alallier** 2020-08-04 12:44 UTC
