### ISSUE TITLE
Feature request - Automatically inject reload script in HTML responses

### ISSUE THREAD

**Issue by hrastnik** [alallier/reload#149] opened 2018-01-29 08:03 UTC
When using reload with express, instead of having to manually add the <script> tag, it could be injected automatically by intercepting the response and overwriting the response data.

I've used this code in my server and it seems to work...

```
reload(app);
app.use(function(req, res, next) {
  const send = res.send;

  res.send = function() {
    if (typeof arguments[0] === "string") {
      arguments[0] = arguments[0].replace(
        "</html>",
        '<script src="/reload/reload.js"></script></html>'
      );
    }
    return send.apply(res, arguments);
  };

  next();
});
```

**Comment by alallier** [comment] 2018-01-29 12:40
Closing duplicate of #12. But I don't see why we can't add this as an option to reload.

**Closed by alallier** 2018-01-29 12:40 UTC
