### ISSUE TITLE
Node v14 seems to break reload

### ISSUE THREAD

**Issue by jeffs** [alallier/reload#243] opened 2020-05-10 21:01 UTC
Reload throws when run with Node v14.  It works properly with Node v12:

```
~ $ nvm use 12 && mkdir v12 && cd v12 && npm init -y && npm i -D reload && ./node_modules/.bin/reload
Now using node v12.13.1 (npm v6.14.4)
. . . .
Reload web server:
listening on port 8080
monitoring dir /home/jeff/v12
```

^^^ As expected.  But with Node v14:
```
~ $ nvm use 14 && mkdir v14 && cd v14 && npm init -y && npm i -D reload && ./node_modules/.bin/reload
Now using node v14.2.0 (npm v6.14.4)
. . . .
Reload web server:
listening on port 8080
monitoring dir /home/jeff/v14
internal/fs/utils.js:658
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1380:5)
    at Server.<anonymous> (/home/jeff/v14/node_modules/reload/lib/reload-server.js:76:10)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:327:22)
    at emitListeningNT (net.js:1348:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

^^^ Reload throws that same exception, again and again.

**Comment by alallier** [comment] 2020-05-11 13:06
Duplicate of #241, closing

**Closed by alallier** 2020-05-11 13:06 UTC

**Comment by alallier** [comment] 2020-05-25 20:35
@jeffs This is taken care of in the new release https://github.com/alallier/reload/releases/tag/3.0.5

**Comment by jeffs** [comment] 2020-05-26 01:18
Fantastic, thanks!  Confirmed, 3.0.5 works for me.
