### ISSUE TITLE
how to use in koa2?

### ISSUE THREAD

**Issue by KaiOrange** [alallier/reload#165] opened 2018-09-09 03:45 UTC
I find this does not seem to support koa2, does it?

**Comment by alallier** [comment] 2018-09-10 11:33
Reload doesn't support koa as of right now. There is an [open issue](#15) about supporting koa. Closing this as a duplicate of that issue. Feel free to continue discussion there or even send up a MR closing that issue.

**Closed by alallier** 2018-09-10 11:33 UTC
